### ISSUE TITLE
peer to peer review

### ISSUE THREAD

**Issue by marilirulita** [Bondok6/Awesome-Books-ES6#4]
Very nice code and the project runs very well!
Extra point the design and visual effects are so cool!

**Comment by gdumani** [comment]
Nice touch using a  the scroll bar in the list!
It woul be nice to create a new module for the timer code!

**Comment by Bondok6** [comment]
## Hey @gdumani , @marilirulita 👋

Thanks for your feedback.
I will implement this change ASAP.

<img src="https://media2.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif"/>
